server:
  port: 8000

spring:
  application:
    name: feign-order-service


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: feignOrder8000
    prefer-ip-address: true     #访问路径可以显示IP地址
#feign:
#  client:
#    config:
#             default:
#                      connectTimeout: 60000
#                      readTimeOut: 60000


#开启日志记录

logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: DEBUG
